import csv
import json
import os
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple

import cv2
import numpy as np


CONFIG = {
    # Original test images.
    "input_dir": r"E:\starry-data\test",

    # Suppression output images, e.g., *_suppressed.png generated by test-zero shot.py.
    "output_dir": r"E:\starry-data\result",

    # Optional GT/pseudo-GT background images. Leave as None if unavailable.
    "gt_background_dir": None,  # r"E:\starry-data\gt_background"

    # Optional background masks for BRR. Leave as None if unavailable.
    "background_mask_dir": None,  # r"E:\starry-data\background_mask"

    # JSON/CSV annotation file with target/background boxes.
    "annotation_path": r"E:\starry-data\annotation.json",

    # CSV output path.
    "save_csv": r"E:\starry-data\result\metrics.csv",
}


Box = Tuple[int, int, int, int]


@dataclass
class RegionAnnotation:
    target_box: Box
    background_box: Box


def to_float_image(img: np.ndarray) -> np.ndarray:
    if img is None:
        raise ValueError("Input image is None.")
    if img.ndim == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.astype(np.float32)
    if img.size > 0 and img.max() > 1.0:
        img /= 255.0
    return img


def read_gray(path: str) -> np.ndarray:
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(path)
    return img


def resize_like(pred: np.ndarray, ref: np.ndarray) -> np.ndarray:
    if pred.shape[:2] == ref.shape[:2]:
        return pred
    return cv2.resize(pred, (ref.shape[1], ref.shape[0]), interpolation=cv2.INTER_LINEAR)


def crop_region(img: np.ndarray, box: Box) -> np.ndarray:
    x1, y1, x2, y2 = [int(v) for v in box]
    h, w = img.shape[:2]
    x1 = max(0, min(x1, w - 1))
    y1 = max(0, min(y1, h - 1))
    x2 = max(0, min(x2, w))
    y2 = max(0, min(y2, h))
    if x2 <= x1 or y2 <= y1:
        raise ValueError(f"Invalid box after clipping: {(x1, y1, x2, y2)}")
    return img[y1:y2, x1:x2]


def psnr(pred: np.ndarray, gt: np.ndarray, eps: float = 1e-8) -> float:
    pred = to_float_image(pred)
    gt = to_float_image(gt)
    pred = resize_like(pred, gt)
    mse = float(np.mean((pred - gt) ** 2))
    return float(10.0 * np.log10(1.0 / (mse + eps)))


def mae(pred: np.ndarray, gt: np.ndarray) -> float:
    pred = to_float_image(pred)
    gt = to_float_image(gt)
    pred = resize_like(pred, gt)
    return float(np.mean(np.abs(pred - gt)))


def ssim_simple(pred: np.ndarray, gt: np.ndarray, c1: float = 0.01 ** 2, c2: float = 0.03 ** 2) -> float:
    pred = to_float_image(pred)
    gt = to_float_image(gt)
    pred = resize_like(pred, gt)
    mu_x = float(np.mean(pred))
    mu_y = float(np.mean(gt))
    sigma_x = float(np.var(pred))
    sigma_y = float(np.var(gt))
    sigma_xy = float(np.mean((pred - mu_x) * (gt - mu_y)))
    return float(((2 * mu_x * mu_y + c1) * (2 * sigma_xy + c2)) /
                 ((mu_x ** 2 + mu_y ** 2 + c1) * (sigma_x + sigma_y + c2)))


def _gradient_magnitude(img: np.ndarray) -> np.ndarray:
    gx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=3)
    return np.sqrt(gx ** 2 + gy ** 2)


def fsim_simple(pred: np.ndarray, gt: np.ndarray, eps: float = 1e-8) -> float:
    """FSIM-like implementation using gradient magnitude similarity.
    This is dependency-free and consistent with edge/structure preservation evaluation.
    """
    pred = to_float_image(pred)
    gt = to_float_image(gt)
    pred = resize_like(pred, gt)
    gm_p = _gradient_magnitude(pred)
    gm_g = _gradient_magnitude(gt)
    t = 0.0026
    sim = (2.0 * gm_p * gm_g + t) / (gm_p ** 2 + gm_g ** 2 + t + eps)
    weight = np.maximum(gm_p, gm_g)
    return float(np.sum(sim * weight) / (np.sum(weight) + eps))


def brr(pred: np.ndarray, gt: np.ndarray, background_mask: Optional[np.ndarray] = None, tau: float = 0.1) -> float:
    pred = to_float_image(pred)
    gt = to_float_image(gt)
    pred = resize_like(pred, gt)
    score_map = np.exp(-np.abs(pred - gt) / max(tau, 1e-8))
    if background_mask is not None:
        mask = background_mask.astype(bool)
        if mask.shape != gt.shape:
            mask = cv2.resize(mask.astype(np.uint8), (gt.shape[1], gt.shape[0]), interpolation=cv2.INTER_NEAREST).astype(bool)
        if np.sum(mask) > 0:
            return float(np.mean(score_map[mask]))
    return float(np.mean(score_map))


def scr(image: np.ndarray, target_box: Box, background_box: Box, eps: float = 1e-8) -> float:
    image = to_float_image(image)
    target = crop_region(image, target_box)
    bg = crop_region(image, background_box)
    return float((np.mean(target) - np.mean(bg)) / (np.std(bg) + eps))


def bsf(input_image: np.ndarray, output_image: np.ndarray, background_box: Box, eps: float = 1e-8) -> float:
    input_image = to_float_image(input_image)
    output_image = to_float_image(output_image)
    output_image = resize_like(output_image, input_image)
    bg_in = crop_region(input_image, background_box)
    bg_out = crop_region(output_image, background_box)
    return float(np.std(bg_in) / (np.std(bg_out) + eps))


def cnr(image: np.ndarray, target_box: Box, background_box: Box, eps: float = 1e-8) -> float:
    image = to_float_image(image)
    target = crop_region(image, target_box)
    bg = crop_region(image, background_box)
    mu_t = float(np.mean(target))
    mu_b = float(np.mean(bg))
    sigma_t = float(np.std(target))
    sigma_b = float(np.std(bg))
    return float(abs(mu_t - mu_b) / (np.sqrt(sigma_t ** 2 + sigma_b ** 2) + eps))


def contrast_gain(input_image: np.ndarray, output_image: np.ndarray, target_box: Box, background_box: Box, eps: float = 1e-8) -> float:
    input_image = to_float_image(input_image)
    output_image = to_float_image(output_image)
    output_image = resize_like(output_image, input_image)
    target_in = crop_region(input_image, target_box)
    bg_in = crop_region(input_image, background_box)
    target_out = crop_region(output_image, target_box)
    bg_out = crop_region(output_image, background_box)
    c_in = abs(float(np.mean(target_in)) - float(np.mean(bg_in)))
    c_out = abs(float(np.mean(target_out)) - float(np.mean(bg_out)))
    return float(c_out / (c_in + eps))


def gzsl_open_set_metrics(gt_is_unseen: Iterable[bool], pred_is_unseen: Iterable[bool],
                          unstable_semantic_response: Optional[Iterable[bool]] = None) -> Dict[str, float]:
    """UDA, FSR, OER.

    FSR follows the revised manuscript definition: it evaluates unstable semantic responses during
    seen/unseen decision making. If an explicit unstable_semantic_response sequence is not provided,
    unseen-to-seen errors are used as a conservative approximation.
    """
    gt = np.asarray(list(gt_is_unseen)).astype(bool)
    pred = np.asarray(list(pred_is_unseen)).astype(bool)
    if gt.shape != pred.shape:
        raise ValueError("gt_is_unseen and pred_is_unseen must have the same length.")
    n_total = len(gt)
    unseen = gt
    n_unseen = int(np.sum(unseen))
    if n_total == 0:
        return {"UDA": 0.0, "FSR": 0.0, "OER": 0.0}
    uda = float(np.sum(pred[unseen]) / max(n_unseen, 1))
    if unstable_semantic_response is not None:
        unstable = np.asarray(list(unstable_semantic_response)).astype(bool)
        fsr = float(np.sum(unstable[unseen]) / max(n_unseen, 1))
    else:
        fsr = float(np.sum((~pred) & unseen) / max(n_unseen, 1))
    oer = float(np.sum(pred != gt) / max(n_total, 1))
    return {"UDA": uda, "FSR": fsr, "OER": oer}


def fisher_ratio(features: np.ndarray, labels: np.ndarray, eps: float = 1e-8) -> float:
    features = np.asarray(features, dtype=np.float64)
    labels = np.asarray(labels)
    overall = np.mean(features, axis=0)
    sb = 0.0
    sw = 0.0
    for c in np.unique(labels):
        x = features[labels == c]
        if len(x) == 0:
            continue
        mu = np.mean(x, axis=0)
        sb += len(x) * np.sum((mu - overall) ** 2)
        sw += np.sum((x - mu) ** 2)
    return float(sb / (sw + eps))


def inter_intra_distance_ratio(features: np.ndarray, labels: np.ndarray, eps: float = 1e-8) -> float:
    features = np.asarray(features, dtype=np.float64)
    labels = np.asarray(labels)
    centers = []
    intra = []
    for c in np.unique(labels):
        x = features[labels == c]
        mu = np.mean(x, axis=0)
        centers.append(mu)
        intra.extend(np.linalg.norm(x - mu, axis=1).tolist())
    centers = np.asarray(centers)
    if len(centers) < 2:
        return 0.0
    dists = []
    for i in range(len(centers)):
        for j in range(i + 1, len(centers)):
            dists.append(np.linalg.norm(centers[i] - centers[j]))
    return float(np.mean(dists) / (np.mean(intra) + eps))


def evaluate_suppression(input_image: np.ndarray, output_image: np.ndarray, target_box: Box, background_box: Box,
                         gt_background: Optional[np.ndarray] = None,
                         background_mask: Optional[np.ndarray] = None) -> Dict[str, float]:
    result = {
        "BSF": bsf(input_image, output_image, background_box),
        "SCR": scr(output_image, target_box, background_box),
        "CNR": cnr(output_image, target_box, background_box),
        "CG": contrast_gain(input_image, output_image, target_box, background_box),
    }
    if gt_background is not None:
        result.update({
            "PSNR": psnr(output_image, gt_background),
            "MAE": mae(output_image, gt_background),
            "SSIM": ssim_simple(output_image, gt_background),
            "FSIM": fsim_simple(output_image, gt_background),
            "BRR": brr(output_image, gt_background, background_mask=background_mask),
        })
    return result


def average_metrics(metric_rows: List[Dict[str, float]]) -> Dict[str, float]:
    if not metric_rows:
        return {}
    keys = sorted(set().union(*[row.keys() for row in metric_rows]))
    avg = {}
    for key in keys:
        vals = [row[key] for row in metric_rows if key in row and np.isfinite(row[key])]
        if vals:
            avg[key] = float(np.mean(vals))
    return avg


def load_annotations(path: str) -> Dict[str, RegionAnnotation]:
    ext = os.path.splitext(path)[1].lower()
    anns: Dict[str, RegionAnnotation] = {}
    if ext == ".json":
        with open(path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        for name, item in obj.items():
            stem = os.path.splitext(name)[0]
            anns[stem] = RegionAnnotation(tuple(item["target_box"]), tuple(item["background_box"]))
        return anns
    if ext == ".csv":
        with open(path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                stem = os.path.splitext(row["name"])[0]
                anns[stem] = RegionAnnotation(
                    (int(row["target_x1"]), int(row["target_y1"]), int(row["target_x2"]), int(row["target_y2"])),
                    (int(row["bg_x1"]), int(row["bg_y1"]), int(row["bg_x2"]), int(row["bg_y2"])),
                )
        return anns
    raise ValueError("annotation_path must be .json or .csv")


def list_images(directory: str) -> List[str]:
    exts = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
    if not directory or not os.path.isdir(directory):
        return []
    return sorted([os.path.join(directory, f) for f in os.listdir(directory) if os.path.splitext(f)[1].lower() in exts])


def find_matching_image(directory: Optional[str], stem: str) -> Optional[str]:
    if not directory or not os.path.isdir(directory):
        return None
    candidates = [stem, stem + "_suppressed", stem + "_background"]
    for c in candidates:
        for ext in [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]:
            path = os.path.join(directory, c + ext)
            if os.path.exists(path):
                return path
    return None


def batch_evaluate() -> None:
    cfg = CONFIG
    anns = load_annotations(cfg["annotation_path"])
    inputs = list_images(cfg["input_dir"])
    rows: List[Dict[str, float]] = []
    os.makedirs(os.path.dirname(cfg["save_csv"]), exist_ok=True)
    for input_path in inputs:
        stem = os.path.splitext(os.path.basename(input_path))[0]
        if stem not in anns:
            print(f"[Skip] no annotation: {stem}")
            continue
        output_path = find_matching_image(cfg["output_dir"], stem)
        if output_path is None:
            print(f"[Skip] no output: {stem}")
            continue
        gt_path = find_matching_image(cfg["gt_background_dir"], stem)
        mask_path = find_matching_image(cfg["background_mask_dir"], stem)
        input_img = read_gray(input_path)
        output_img = read_gray(output_path)
        gt_img = read_gray(gt_path) if gt_path else None
        bg_mask = read_gray(mask_path) > 0 if mask_path else None
        m = evaluate_suppression(input_img, output_img, anns[stem].target_box, anns[stem].background_box, gt_img, bg_mask)
        row = {"name": stem}
        row.update(m)
        rows.append(row)
        print(stem, {k: round(v, 4) for k, v in m.items()})
    avg = average_metrics([{k: v for k, v in r.items() if k != "name"} for r in rows])
    if rows:
        keys = ["name"] + sorted([k for k in rows[0].keys() if k != "name"])
        with open(cfg["save_csv"], "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            for r in rows:
                writer.writerow(r)
            avg_row = {"name": "Average"}
            avg_row.update(avg)
            writer.writerow(avg_row)
    print("Average:", {k: round(v, 4) for k, v in avg.items()})
    print(f"Saved to: {cfg['save_csv']}")
